spring.application.name=demoday1

spring.threads.virtual.enabled=true

spring.jpa.show-sql=true

logging.level.org.hibernate.engine.transaction.internal.TransactionImpl=DEBUG
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.transaction=DEBUG